language: csharp
sudo: required
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build src/nniversaryReminder.csproj
 - dotnet test test/AnniversaryReminder.Tests/AnniversaryReminder.Tests.csproj