language: node_js

node_js:
- "10"

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

matrix:
  include:
    - os: linux
      dist: bionic # Ubuntu 18.04
      dotnet: 3.1.101
      mono: none
      env:
        - DOTNETCORE=3
        - CXX="g++-7.4"
        - CC="gcc-7.4"
        - DISPLAY=:99.0
      sudo: required
      before_install:
        - Xcfb :99 & sleep 3
        - dpkg --compare-versions `npm -v` ge 6.7 || npm i -g npm@^6.7
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install apt-transport-https
        - sudo apt-get update

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - libsecret-1-dev

    - os: osx
      dotnet: 3.1.101
      mono: none
      env: DOTNETCORE=3
      before_install:
        - chmod a+x ./runtests.sh
        - ulimit -n 1024 ;

#        - brew install mariadb
#        - brew services start mariadb
#        - brew install redis
#        - brew services start redis

# services:
#  - mysql
#  - redis-server

before_install:
  #  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('1qazZAQ!') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - chmod a+x ./runtests.sh

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export TRAVIS=1
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then
    sudo apt-get install dotnet-sdk-3.1
    sudo apt-get install xvfb
    fi
  - if [["$TRAVIS_OS_NAME" == "macos"]]; then
    brew update
    brew cask install dotnet-sdk
    fi

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-dupe --allow-redirect
  - ./runtests.sh
