---
version: '0.2'
language: en
files:
  - .github/**/*.{md,txt,yaml,yml}
  - .git/COMMIT_EDITMSG
  - '*.{md,txt,yaml,yml}'
  - dictionaries/**/*.{md,txt,yaml,yml,js,tex}
  - docs/**/*.md
  - scripts/**
  - src/**
  - tests/**
  - shared-sources/**
words:
  - Jürgen
  - Mülbert
  - jmuelbert
  - jmbde
  - Akka
  - Astro
  - Autobuild
  - autolabeler
  - Bazel
  - Bitstream
  - Codecov
  - Codacy
  - Colab
  - commitlint
  - Cuda
  - codeql
  - dessant
  - devskim
  - devcontainers
  - fsfe
  - ghaction
  - gittools
  - gsoc
  - lengthframeencoder
  - matthiashermsen
  - MSDO
  - mshick
  - OSSAR
  - ossf
  - outreachy
  - Preacts
  - rarr
  - recvbuffer
  - returntocorp
  - Sarif
  - Semgrep
  - Signup
  - sobolevn
  - srggrs
  - stefanzweifel
  - tomwhross
  - tsconfigs
  - Unported
  - wagoid
  - withastro

flagWords:
  - hte
maxNumberOfProblems: 1000
ignorePaths:
  - .devcontainer/.dockerignore
  - .git
  - .github/actions/spelling/**
  - .github/labels.yml
  - .github/pr-labeler.yml
  - .gitattributes
  - .gitignore
  - .vscode/**
  - '*.lock'
  - '*-lock.yaml'
  - '*.log'
  - '*.aff'
  - '*.dic'
  - '*.gz'
  - '*.snap'
  - '*.trie'
  - '**/.git/!(COMMIT_EDITMSG)'
  - '**/.git/!(COMMIT_EDITMSG)/**'
  - CHANGELOG.md
  - checksum.txt
  - cSpell.json
  - cspell.json
  - cspell.config.yaml
  - LICENSE
  - LICENSES/**
  - node_modules
  - package.json
  - .prettierignore
  - shared-additional-words.txt
  - source-dependencies.txt
  - source-files.txt
  - snapshots/**
  - ./project-words.txt
import: []
useGitignore: true
overrides:
  - filename: '**/de_DE/**'
    language: en,de
  - filename: '**/nl_NL/**'
    language: en,nl
  - filename: '**/ru_RU/samples/**'
    language: ru,en
  - filename: '**/sv/**'
    language: en,sv
  - filename: 'package.json'
    ignoreWords:
      - colour
      - canot
cache:
  useCache: true
  cacheStrategy: content
enableFiletypes:
  - shellscript
dictionaryDefinitions:
  - name: ./project-words
    addWords: true
    scope:
      - workspace
    path: ./project-words.txt
dictionaries:
  - ./project-words
  - bash
  - companies
  - csharp
  - css
  - filetypes
  - fonts
  - misc
  - node
  - npm
  - powershell
  - python
  - software-terms
  - typescript
