---
version: '0.2'
files:
  - '**/*'
dictionaries:
  - taskfile
  - bash
  - docker
ignorePaths:
  - s**/node_modules/**
  - '**/vscode-extension/**'
  - '**/.git/**'
  - '.github/actions/**'
  - '.github/workflows/**'
  - '.github/labels.yml'
  - 'docs/api-docs/**'
  - 'cspell.config.yaml'
  - '.codespell.rc'
  - '*.gz'
  - '*.lock'
  - '*.svg'
  - .gitignore
  - .gitattributes
  - .devcontainer/.dockerignore
  - .vscode
  - megalinter
  - package-lock.json
  - report
  - pnpm-lock.yaml
  - dist/**
  - build/**
  - out/**
  - /project-words.txt
  - ./qt-words.txt
  - ./taskfile-words.txt
  - ./cmake-refined-words.txt
  - ./linux-package-words.txt
useGitignore: true
language: en, en-GB, de, de-DE
allowCompoundWords: true
enableGlobDot: true
words:
  - APPL
  - ARGN
  - asdict
  - cbproj
  - Codacy
  - codecov
  - Devel
  - DCOMPONENT
  - DOPTION*
  - DPROJECT
  - eamodio
  - fasterer
  - FILEOS
  - fips
  - ftest
  - fprofile
  - furo
  - Fuzzer
  - Gcov
  - giticket
  - groupproj
  - gtest
  - HADOLINT
  - hmarr
  - hwrap
  - icns
  - idiv
  - IHELP
  - IOPTIONS
  - itertools
  - IQUIT
  - IWYU
  - jamf
  - jinja
  - jmuelbert
  - juergen
  - kondo
  - kwarg
  - kwargs
  - LCOV
  - muelbert
  - Mülbert
  - mkdocs
  - msvs
  - munki
  - munkiadmin
  - munkipkg
  - myclass
  - mypackage
  - mypy
  - noqa
  - parg
  - pargs
  - Pavlik
  - Pboard
  - plists
  - pipenv
  - pkgsinfo
  - PTRACE
  - pthread
  - pthreads
  - pydocstyle
  - pylance
  - pylint
  - PYRIGHT
  - pyyaml
  - rdiv
  - REDIST
  - rgxs
  - SAST
  - sectnums
  - socat
  - sonarqube
  - spdlog
  - svgz
  - SYSREQUIRES
  - tetris
  - tkinter
  - rubocop
  - TRIVY
  - twxs
  - venv
  - VRAC
  - webp
  - Wignored
  - winver
  - xreadlines
  - xrange
