---
name: "Check Format"

on:
    push:
        branches:
            - develop
    pull_request:
        types:
            - assigned
            - opened
            - synchronize
            - reopened

jobs:
  format:
    name: "Check Clang Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install clang-format-9"
        run: |
          sudo apt-get update
