---
# SPDX-FileCopyrightText: (c) Wagner Santos
#
# SPDX-License-Identifier: MIT
#
name: Lint Commit Messages
on: [pull_request]

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Checkout"
        uses: actions/checkout@v4

      - name: "Check the commits"
        uses: wagoid/commitlint-github-action@v5
