---
name: "GitHub Labeler"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"
  pull_request:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "🧰 Check out code"
        uses: actions/checkout@v3

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          exclude: |
            help*
            *issue
