---
name: Style

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'docker/**'
      - '**.md'
      - '!docs/building-cmake.md'
      - 'changelog.txt'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/styles.yml'
      - 'snap/**'
      - 'build/**'
      - 'assets/**'
      - 'Docker/**'
      - 'report/**'
      - 'resources/**'
  pull_request:
    branches:
      - 'master'
    types: [opened, reopened]
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'docker/**'
      - '**.md'
      - '!docs/building-cmake.md'
      - 'changelog.txt'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/styles.yml'
      - 'snap/**'
      - 'build/**'
      - 'assets/**'
      - 'Docker/**'
      - 'report/**'
      - 'resources/**'

  release:
    types: [published]

on:
  push:
    branches:
      - master
      - "fix/*"
      - "feature/*"

  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    name: DotNet Format
    steps:
      - uses: actions/checkout@v2
      - run: dotnet tool install -g dotnet-format
      - run: dotnet format ./ --folder --check --exclude **/AddFormats/
